ionic g page Login
ionic g page Chat
ionic g component SearchSelectPopover
ionic g component SearchSelectMuli
ionic g component SpinnerPopover
ionic g provider User
ionic g provider Bot
ionic platform add android
ionic plugin add cordova-plugin-geolocation
npm install --save @ionic-native/geolocation
npm install --save @ionic-native/core
